Feature/interface pro
re-connect/vault pull request #14
Opened 2023-02-14 09:46 UTC by AntoineAresu

2023-02-14 14:22 UTC, NilsRec commented on tests/v2/Controller/ContactController/SwitchPrivateTest.php
> +        yield 'Should redirect to list code authenticated as beneficiaire' => [self::URL, 302, BeneficiaryFixture::BENEFICIARY_MAIL, '/beneficiary/%s/contacts'];
"Should redirect to list `code` authenticated as beneficiaire " --> petite faute

2023-02-14 14:58 UTC, tcheymol commented on translations/messages.en.yml
> +leave: Leave
Ces délicieuses traductions sont elles renseignées dans le superbe fichier excel ?

2023-02-14 14:58 UTC, tcheymol commented on src/ControllerV2/EventController.php
> +            : $this->redirectToRoute('event_list', ['id' => $event->getBeneficiaire()->getId()]);
J'aurais tendance à bien aimer avoir une méthode genre `$event->getBeneficiaryId()`, je pense que ça permet mieux de gérer les cas de nullité et d'être serein sur ces cas, pareiul pour doc, contact, etc

2023-02-14 14:58 UTC, tcheymol commented on templates/components/event_form.html.twig
> +            class="btn {{ getUserButtonColor()}} text-white mb-2"
Il manque un espace avant le `}}`

2023-02-14 14:58 UTC, tcheymol commented on templates/components/event_form.html.twig
> +        {{ button('submit', 'confirm', app.user.isBeneficiaire ? 'green' : 'blue') }}
Tu peux pas utilser ta délicieuse extensions ici ?

2023-02-14 14:58 UTC, tcheymol commented on templates/v2/vault/components/_personal_data_detail.html.twig
> +                    app.user.isBeneficiaire ? 'green' : 'blue',
Same here

2023-02-14 14:58 UTC, tcheymol commented on templates/v2/vault/form/_personal_data_form.html.twig
> +                app.user.isBeneficiaire ? 'green' : 'blue',
On aurait pas un boutton générique carrément qui pourrait faire la décision ?

2023-02-14 15:08 UTC, tcheymol requested changes

2023-02-14 15:08 UTC, tcheymol commented on templates/v2/vault/nav/pro/_pro_nav_item.html.twig
> +{% set route = app.request.attributes.get('_route')|split('_') %}
On pourrait pas mettre en commun les 2 temppates ? 🥹

2023-02-14 15:08 UTC, tcheymol commented on templates/v2/vault/folder/_card.html.twig
> +                <i class="fas fa-file-download {{ getUserTextColor() }}"
Je pense que j'aurais tendance à mettre ça dans un composant pour utiliser le moins possible `getUserTextColor()`

Une autre solution aurait été aussi d'avoir 2 fichiers css, et d'utiliser la même classe `user-button` ou `user-text` et d'inclure selon le cas bénef ou pro un fichier css différent, ça aurait déplacé les responsabilités en un seul endroit

2023-02-15 14:45 UTC, AntoineAresu commented on templates/v2/vault/nav/pro/_pro_nav_item.html.twig
> +{% set route = app.request.attributes.get('_route')|split('_') %}
On pourrait, ce qui les différencie c'est surtout les nombreuses classes CSS. Le problème en refactorisant, et par exemple en faisant un include d'un template commun, il faudrait passer les variables correspondantes à ces classes CSS. J'ai l'impression que ce ne sera pas vraiment plus pratique, et on perd l'autocompletion sur les classes CSS.

```
{% set listItemClasses = isBeneficiary
    ? 'col list-group vault-nav-item pro-nav-item mt-3 mt-sm-0 px-0'
    : 'col vault-nav-item beneficiary-nav-item'  %}
<li class="{{ listItemClasses }}">

ou 

{{ include('v2/vault/nav/_nav_item.html.twig', {
    'listItemClasses': 'col list-group vault-nav-item pro-nav-item mt-3 mt-sm-0 px-0',
```

2023-02-15 15:14 UTC, AntoineAresu commented on templates/v2/vault/form/_personal_data_form.html.twig
> +                app.user.isBeneficiaire ? 'green' : 'blue',
`<button class="btn btn-{{ color }} text-white text-center mt-2 col mx-1" type="{{ type }}">`
On a un bouton générique, et il l'est justement parce qu'on peut choisir n'importe quelle couleur qui existe quand on appel la fonction button().
Je pense que c'est bien qu'il reste générique, par contre, on peut avoir une fonction getUserColor() qui retourne 'green' ou 'blue' dans notre UserColorExtension, et la passer en paramètre de button()

2023-02-15 16:17 UTC, AntoineAresu commented on templates/v2/vault/nav/beneficiary/_beneficiary_nav.html.twig
> +                {% for key, item in itemsList %}
Pour quelles raisons ?

2023-02-21 10:42 UTC, closed without merging